<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>13.0</LangVersion>
    <Version>2.0.0.0</Version>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Templates\HtmlSpoiler.tt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Templates\HtmlSpoiler.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>HtmlSpoiler.cs</LastGenOutput>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Be.IO-multi" Version="1.0.0" />
    <PackageReference Include="DynamicExpresso.Core" Version="2.16.1" />
    <PackageReference Include="Microsoft.Toolkit.HighPerformance" Version="6.1.1" />
    <PackageReference Include="SixLabors.ImageSharp" Version="1.0.0-beta0007" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="1.0.0-beta0007" />
    <PackageReference Include="System.CodeDom" Version="4.7.0" />
    <PackageReference Include="VCDiff" Version="3.2.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MMR.Common\MMR.Common.csproj" />
    <ProjectReference Include="..\MMR.Yaz\MMR.Yaz.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\addresses.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>addresses.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\asm.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>asm.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\models.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>models.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\mods.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>mods.resx</DependentUpon>
    </Compile>
    <Compile Update="Templates\HtmlSpoiler.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>HtmlSpoiler.tt</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="music\botw-hyrulecastle.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\botw-kass.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\mk64-battle.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\mk64-bb.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\mk64-bc.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\mk64-ceremony-loss.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\mk64-ceremony.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\mk64-cm.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\mk64-dkjp.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\mk64-fs.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\mk64-kb.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\mk64-kd.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\mk64-lr.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\mk64-menu.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\mk64-mmf.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\mk64-rr.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\mk64-star.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\mk64-tt.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\mmr-jazz.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\mmr-theme.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-boss.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-c-goddess.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-castlecollapse.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-castlecourtyard.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-chamberofsages.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-dekutree.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-dinosaur.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-dodongocavern.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-f-ganondorf.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-f-medallion.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-f-opendot.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-f-stone.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-f-timetravel.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-firetemple.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-foresttemple.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-ganon.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-ganoncastle.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-ganondorf.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-ganondorfbattle.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-gerudovalley.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-icecavern.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-insidedekutree.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-jabu.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-kakariko1.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-kakariko2.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-kokiriforest.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-market.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-miniboss.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-navi.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-shadowtemple.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-sheik.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-spirittemple.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-templeoftime.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\oot-watertemple.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\pa-ikanacastle.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\pm-field.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sf64-aquas.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sf64-area6.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sf64-bolse.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sf64-boss1.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sf64-boss2.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sf64-boss3.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sf64-corneria.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sf64-fichina.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sf64-katarina.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sf64-meteo.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sf64-sectorx.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sf64-sectory.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sf64-starwolf.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sf64-titania.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sf64-venom.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sf64-zoness.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sm64-battlefield.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sm64-bbh.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sm64-bitdw.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sm64-boss.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sm64-castle.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sm64-ccm.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sm64-f-bitsclear.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sm64-f-bowser.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sm64-f-bowserclear.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sm64-f-intro.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sm64-f-lakitu.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sm64-f-peach.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sm64-f-race.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sm64-f-savepeach.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sm64-f-solved.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sm64-f-star.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sm64-f-starget.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sm64-f-toad.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sm64-f-unlock.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sm64-fileselect.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sm64-finalbowser.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sm64-hmc.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sm64-jrb.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sm64-lll.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sm64-lullaby.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sm64-mgr.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sm64-slide.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\sm64-steps.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\smg2-skystation.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\ss-groose.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\uc-boss.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\uc-dekuforest.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\uc-dekutree.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\uc-dream.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\uc-dungeon.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\uc-field.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\uc-fileselect.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\uc-foresttemple.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\uc-gerudobay.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\uc-goronvillage.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\uc-miniboss.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\uc-minigame.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\uc-mountain.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\uc-navi.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\uc-predungeon.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\uc-snowfield.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\uc-snowfieldold.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\uc-village.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\uc-zelda.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="music\uc-zora.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\addresses.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>addresses.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\asm.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>asm.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\models.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>models.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\mods.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>mods.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
