<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Version>2.0.0.0</Version>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Templates\HtmlSpoiler.tt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Templates\HtmlSpoiler.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>HtmlSpoiler.cs</LastGenOutput>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Be.IO-multi" Version="1.0.0" />
    <PackageReference Include="CommunityToolkit.HighPerformance" Version="8.4.2" />
    <PackageReference Include="DynamicExpresso.Core" Version="2.19.3" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.7" />
    <PackageReference Include="System.CodeDom" Version="10.0.7" />
    <PackageReference Include="VCDiff" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MMR.Common\MMR.Common.csproj" />
    <ProjectReference Include="..\MMR.Yaz\MMR.Yaz.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\addresses.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>addresses.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\asm.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>asm.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\models.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>models.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\mods.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>mods.resx</DependentUpon>
    </Compile>
    <Compile Update="Templates\HtmlSpoiler.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>HtmlSpoiler.tt</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="music\**\*.mmrs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\addresses.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>addresses.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\asm.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>asm.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\models.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>models.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\mods.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>mods.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
