<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>13.0</LangVersion>
    <ApplicationIcon>200px_majoramask_rtw_icon.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" Version="1.0.0-beta0007" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="1.0.0-beta0007" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MMR.Randomizer\MMR.Randomizer.csproj" />
  </ItemGroup>

</Project>
